name: Update PR List

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate PR list
        id: prlist
        run: |
          curl -s "https://api.github.com/search/issues?q=author:scars97+type:pr&sort=created&order=desc&per_page=3" \
          | jq '.items[] | "- [\(.repository_url | split("/")[-1])] \(.title)(\(.html_url))"' \
          > pr_list.md

      - name: Update README.md with PR list
        run: |
          awk '
            /<!-- PR-START -->/ {print; system("cat pr_list.md"); skip=1; next}
            /<!-- PR-END -->/ {skip=0}
            !skip
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update PR list"
          add: "README.md"
          default_author: github_actions
